### ISSUE TITLE
JSON06Serialiser is not able to serialise frozen elements

### ISSUE THREAD

**Issue by honzajavorek** [refractproject/minim#144]
Following code

```js
new JSON06Serialiser(fury.minim).serialise(element);
```

blows up when provided with API Elements, which has been previously frozen:

```js
element.freeze();
```

I'm getting exceptions like this one:

```
TypeError: Can't add property _attributes, object is not extensible
      at constructor.get (node_modules/minim/lib/primitives/element.js:295:26)
      at constructor.shouldRefract (node_modules/minim/lib/serialisers/json-0.6.js:217:16)
      at constructor.convertKeyToRefract (node_modules/minim/lib/serialisers/json-0.6.js:250:18)
      at constructor.<anonymous> (node_modules/minim/lib/serialisers/json-0.6.js:288:26)
      at Array.forEach (native)
      at constructor.serialiseObject (node_modules/minim/lib/serialisers/json-0.6.js:287:16)
      at constructor.serialise (node_modules/minim/lib/serialisers/json-0.6.js:19:30)
      at Array.map (native)
      at constructor.serialiseContent (node_modules/minim/lib/serialisers/json-0.6.js:190:22)
      at constructor.serialise (node_modules/minim/lib/serialisers/json-0.6.js:42:33)
      at module.exports (src/api-elements-to-refract.coffee:10:36)
      at compile (src/compile.coffee:19:13)
      at test/utils.coffee:26:16
      at src/parse.coffee:39:5
      at node_modules/fury/lib/fury.js:169:13
      at node_modules/fury-adapter-apib-parser/lib/adapter.js:71:7
```

This blocks https://github.com/apiaryio/dredd-transactions/pull/88.

**Comment by kylef** [comment]
This was resolved, there have been changed in both the Swagger adapter and minim.
